name: CI

on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Functions Dependencies
        working-directory: ./functions
        run: npm install
      - name: Run lint
        working-directory: ./functions
        run: npm run lint
